### ISSUE TITLE
TODO: documentation and examples

### ISSUE THREAD

**Issue by gowestyang** [gowestyang/grandma-stock-valuation#2]
Documentation
- [x] assumptions, methodologies, considerations, limitations
- [x] definitions
- [ ] contribution guidelines

Examples
- [x] Include more packaged data to allow execution without data query
- [x] Separate examples of each functionality
