### ISSUE TITLE
TODO: Also output correlation matrix when calculating correlation weights

### ISSUE THREAD

**Issue by gowestyang** [gowestyang/grandma-stock-valuation#5]

**Comment by gowestyang** [comment]
- [ ] Portfolio Allocation: output correlation matrix when calculating correlation weights
- [ ] Valuation: min_train_years and max_train_years
- [ ] Valuation: option to not draw chart
- [ ] Valuation: option to not clean input data
